### ISSUE TITLE
Could you please add a delay field for DNS resolution? (New feature request)

### ISSUE THREAD

**Issue by heyzqq** [sun0day/dns-selector#1]
_Thank you for being open source!_

Recently, I encountered a problem that **the delay in DNS resolution** is too long. Could you please add a new feature for DNS resolution delay?

It may look as follows:

```
$ dns --host zqq.com --server 114.114.114.114

[=   ] Resolving <zqq.com> IP...

114.114.114.114    116.8.8.80   25ms
8.8.8.8            116.8.8.80   40ms
...
```

**Comment by sun0day** [comment]
Nice. I will handle that
