### ISSUE TITLE
能支持node19吗

### ISSUE THREAD

**Issue by chuyueye** [sun0day/dns-selector#2]
19的api应该改变不多吧

**Comment by sun0day** [comment]
可以的

**Comment by chuyueye** [comment]
目前调用的时候还是提示版本不兼容

**Comment by sun0day** [comment]
这块还没做，后面会兼容，如果感兴趣，可以提个 PR

**Comment by chuyueye** [comment]
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:readline/promises
    at new NodeError (node:internal/errors:387:5)
    at ESMLoader.builtinStrategy (node:internal/modules/esm/translators:259:11)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}
目前node16是不是也没兼容

**Comment by sun0day** [comment]
node16 不在考虑范围内，只从 18.x 向后兼容， readme 里有写依赖的版本

**Comment by sun0day** [comment]
1.1.0 版本支持 node19 了
